baseURL: https://joshsgarden.netlify.com
languageCode: en-us
title: Josh's Plants
theme: hugo-fresh
googleAnalytics: #Put in your tracking code without quotes like this: UA-XXXXXX...
#Disables warningss
disableKinds:
 -taxonomy
 -taxonomyTerm

params:
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: cactus-17.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Josh's Garden
    # Hero subtitle (optional)
    subtitle: My collection of succulents and cacti as a piece of home in Boston.
    # Button text
    buttontext: Check out my projects
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: All Plants
    url: /
  - title: Projects
    sublinks:
    - title: Project 1
      url: /
    - title: Project 2
      url: /
    - title: Project 3
      url: /
  - title: Posts
    url: /
  - title: About
    url: /
  - title: Contact
    url: /
    button: true
  section1:
    title: Featured Projects
    subtitle: Some of my most recent and exciting projects.
    tiles:
    - title: "From Seed: Lithops (I)"
      icon: mouse-globe
      text: First attempt at growing "living stones" from seed.
      url: /
      buttonText: Project Page
    - title: "From Seed: Lithops (II)"
      icon: mouse-globe
      text: Second attempt at growing "living stones" from seed.
      url: /
      buttonText: Project Page
    - title: "From Seed: Astrophytum"
      icon: mouse-globe
      text: First attempt at growing Astrophytum from seed.
      url: /
      buttonText: Project Page
  section2:
    title: Species Collections
    subtitle: I have small collections of a few succulent species.
    features:
    - title: Lithops
      text: These "living stones" are native to the dry, arid South African deserts where they see around just 2 inches of annual rainfall. I love their simplisitic, yet diverse designs and facinating yearly life-cycle.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Haworthia
      text: This common species makes wonderful house-plants because of their relatively low-light and care requirements. Their beautiful shapes and textures draw me in. 
      icon: doc-sync
  section3:
    title: Homemade Artifical LED Lighting System
    subtitle: These plants need much more light than Boston can provide.
    image: illustrations/mockups/app-mockup.png
    buttonText: Build Guide
    buttonLink: "#"
  # section4:
#     title: Our Clients love us!
#     subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
#     clients:
#     - name: Irma Walters
#       quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#       job: Accountant
#       img: 1
#     - name: John Bradley
#       quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#       job: Financial Analyst
#       img: 2
#     - name: Gary Blackman
#       quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#       job: HR Manager
#       img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://joshuacook.netlify.com
      icon: user
    - link: https://twitter.com/JoshDoesa
      icon: twitter
    - link: https://github.com/jhrcook
      icon: github
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
